### ISSUE TITLE
Issue with testsuite: terraform-docs is not installed

### ISSUE THREAD

**Issue by njoerd114** [JamesWoolfenden/terraform-aws-budget#6]
I noticed some issues with the terraform-docs part of the "security" section with your github action:
https://github.com/JamesWoolfenden/terraform-aws-budget/runs/5138356361?check_suite_focus=true

Can you please make sure terraform-docs is installed? Unfortunately, I don't have any experience with github-actions at all...

**Comment by JamesWoolfenden** [comment]
Yeah this must be a glitch as its very much installed, i will take a look. Ill merge the pr anyway and fix if required. The main this is just to ensure that youve used the pre-commits.

**Comment by JamesWoolfenden** [comment]
Ha you were right, shows how i never use the PR on my own repos! Fixed!
